name: Build

on: [push]

jobs:
  Build:
    runs-on: ubuntu-latest
    steps:

    # Checkout the repository.
    - name: Checkout
      uses: actions/checkout@v3

    # Install the prerequisites.
    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install fonts-ibm-plex
        sudo apt-get install texlive
        sudo apt-get install texlive-xetex
        sudo apt-get install texlive-formats-extra

    # Compile the PDF, run xelatex twice to resolve all dependencies.
    - name: Compile
      run: |
        xelatex resume.tex && xelatex resume.tex

    # Upload the PDF as a build artifact with a short retention.
    - name: Upload
      uses: actions/upload-artifact@v3
      with:
        name: resume-${{github.sha}}
        path: resume.pdf
        retention-days: 1

    # Strip the release version from the 'vXXX' tag.
    - name: Release - get ID
      id: version
      if: startsWith(github.ref, 'refs/tags/v')
      run: |
        version=$(echo "${{github.ref_name}}" | sed 's/^v//')
        echo "::set-output name=version::${version}"

    # Rename the PDF file.
    - name: Release - package artifacts
      if: startsWith(github.ref, 'refs/tags/v')
      run: |
        cp resume.pdf resume-${{steps.version.outputs.version}}.pdf

    # For release tags, upload the PDF as part of the release.
    - name: Release - create
      uses: softprops/action-gh-release@v1
      if: startsWith(github.ref, 'refs/tags/v')
      with:
        name: resume-${{steps.version.outputs.version}}
        files: resume-${{steps.version.outputs.version}}.pdf
